spring:
  datasource:
    username: testuser
    password: testing123
    url: jdbc:mariadb://localhost:3306/novussfederation_db
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: testuser
    password: testing123
    url: jdbc:mariadb://localhost:3306/novussfederation_db
    change-log: classpath:db/master.xml

logging:
  level:
    com.novuss.authservice: DEBUG

server:
  error:
    include-message: always
  port: 8000