version: '3'
services:
  db:
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: hm!j034
      MYSQL_DATABASE: novuss_db
    volumes:
      - /path/on/host:/var/lib/mysql
    networks:
      - backend


  restful-service:
    build: ./restful-service
    ports:
      - 8080:8080
    links:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: database
      DB_USER: dbuser
      DB_PASSWORD: password
    networks:
      - backend


  admin-panel:
    build: ./admin-panel
    ports:
      - 3000:3000
    links:
      - restful-service
    environment:
      SERVICE_URL: http://restful-service:8080
    networks:
      - frontend


  public-page:
    build: ./public-page
    ports:
      - 4000:4000
    links:
      - restful-service
    environment:
      SERVICE_URL: http://restful-service:8080
    networks:
      - frontend

      
  adminer:
    image: adminer
    ports:
      - 8080:8080
    networks:
      - backend
networks:
  backend:
  frontend:
