version: '1'

services:
  database:
    container_name: novuss-db-container
    image: "mariadb:10.5"
    volumes:
      - db-data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # REST API USER configuration
      REST_API_DB_USER: ${REST_API_DB_USER}
      REST_API_DB_USER_PASSWORD: ${REST_API_DB_USER_PASSWORD}
      # Auth service USER configuration
      AUTH_SERVICE_DB_USER: ${AUTH_SERVICE_DB_USER}
      AUTH_SERVICE_DB_USER_PASSWORD: ${AUTH_SERVICE_DB_USER_PASSWORD}
    command: --init-file /docker-entrypoint-initdb.d/init.sql
    networks:
      - bachelor-project-network

  adminer:
    container_name: novuss-adminer-container
    image: adminer
    restart: on-failure:5
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      - ADMINER_DEFAULT_SERVER=${DB_HOST}
      - ADMINER_DEFAULT_USERNAME=${DB_USER}
      - ADMINER_DEFAULT_PASSWORD=${DB_PASSWORD}
      - ADMINER_DESIGN=vagrant

    networks:
      - bachelor-project-network

  auth-service:
    container_name: novuss-auth-service-container
    build: ./auth-service
    depends_on:
      - database
    ports:
      - ${AUTH_SERVICE_PORT}:8081
    environment:
      - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
      - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}
      - AUTH_SERVICE_DB_USER=${AUTH_SERVICE_DB_USER}
      - AUTH_SERVICE_DB_PASSWORD=${AUTH_SERVICE_DB_USER_PASSWORD}
    networks:
      - bachelor-project-network

  # restful-service:
  #   container_name: novuss-restful-service-container
  #   build: ./restful-service
  #   depends_on:
  #     - database
  #   ports:
  #     - ${RESTFUL_SERVICE_PORT}:8081
  #   environment:
  #     - SPRING_DATASOURCE_URL=${SPRING_DATASOURCE_URL}
  #     - SPRING_DATASOURCE_DRIVER=${SPRING_DATASOURCE_DRIVER}
  #     - RESTFUL_SERVICE_DB_USER=${RESTFUL_SERVICE_DB_USER}
  #     - RESTFUL_SERVICE_DB_PASSWORD=${RESTFUL_SERVICE_DB_PASSWORD}
  #   networks:
  #     - bachelor-project-network


volumes:
  db-data:

networks:
  bachelor-project-network:
