version: '1'

services:
  database:
    container_name: database-container
    build: ./mysql
    image: "mariadb:10.5.8"
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: novuss_db
      MYSQL_USER: novuss_user
      MYSQL_PASSWORD: enU03tr&xzC9
      MYSQL_ROOT_PASSWORD: enU03tr&xzC9
    networks:
      - project-network

  database-admin:
    container_name: adminer-container
    image: adminer
    ports:
      - 8081:8080
    networks:
      - project-network

  restful-service:
    container_name: restful-service-container
    build: ./restful-service
    restart: always
    ports:
      - "8080:8080"
    networks:
      - project-network
    
  website:
    container_name: website-container
    build: ./website
    restart: always
    ports:
      - "3000:3000"
    networks:
      - project-network


networks:
  project-network:
