version: '1'

services:
  database:
    container_name: novuss-db-container
    image: "mariadb:10.5"
    volumes:
      - db-data:/var/lib/mysql
    restart: on-failure:5
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5
    ports:
      - ${DB_PORT}:3306
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
      MYSQL_USER: ${DB_USER}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      # REST API USER configuration
      REST_API_DB_USER: ${REST_API_DB_USER}
      REST_API_DB_USER_PASSWORD: ${REST_API_DB_USER_PASSWORD}
      # Auth service USER configuration
      AUTH_SERVICE_DB_USER: ${AUTH_SERVICE_DB_USER}
      AUTH_SERVICE_DB_USER_PASSWORD: ${AUTH_SERVICE_DB_USER_PASSWORD}
      # File uploads USER configuration
      FILE_USER: ${FILE_USER}
      FILE_USER_PASSWORD: ${FILE_USER_PASSWORD}
    #command:
      #- /docker-entrypoint-initdb.d/create_file_rw_user.sh
    networks:
      - bachelor-project-network

  adminer:
    container_name: novuss-adminer-container
    image: adminer
    restart: on-failure:5
    ports:
      - ${ADMINER_PORT}:8080
    environment:
      ADMINER_DEFAULT_SERVER: ${DB_HOST}
      ADMINER_DEFAULT_USERNAME: ${DB_USER}
      ADMINER_DEFAULT_PASSWORD: ${DB_PASSWORD}
      ADMINER_DESIGN: vagrant
    networks:
      - bachelor-project-network

volumes:
  db-data:
  file-uploads:
    driver:
      local

networks:
  bachelor-project-network:
    driver: bridge

