spring:
  mariadb:
    console:
      enabled: true
      path: /mariadb-console

  datasource:
    username: novuss_user
    password: enU03tr&xzC9
    url: jdbc:mariadb://localhost:3306/novuss_db?allowMultiQueries=true
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      # TODO: production should be update
      ddl-auto: create-drop
    show-sql: false

  liquibase:
    user: novuss_user
    password: enU03tr&xzC9
    url: jdbc:mariadb://localhost:3306/novuss_db
    change-log: classpath:db/master.xml

  server:
    error:
        include-message: always
    port: 8081

  logging:
    level:
      com.novuss: DEBUG
