spring:

  datasource:
    username: testuser
    password: testing123
    url: jdbc:mariadb://localhost:3306/novussfederation_db
    driver-class-name: org.mariadb.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: false

  liquibase:
    user: testuser
    password: testing123
    url: jdbc:mariadb://localhost:3306/novussfederation_db
    change-log: classpath:db/master.xml

  servlet:
    multipart:
      enabled: true
      file-size-threshold: 2KB
      max-file-size: 10MB
      max-request-size: 10MB
      location: var/uploads

logging:
  level:
    com.novuss: DEBUG

server:
  error:
    include-message: always
  port: 8001

